# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Java Version
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.2

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.3.0
maven_group=com.example.addenchanted
archives_base_name=unlimited-combination-enchantment

# Dependencies
fabric_version=0.157.0+26.2